### ISSUE TITLE
update README to say from partial_json_parser.core.options import *

### ISSUE THREAD

**Issue by runvnc** [promplate/partial-json-parser#9]
Love your module, thanks. I think the line in the readme needs to be updated as per the example:

from partial_json_parser.core.options import *

instead of partial_json_parser.options

**Comment by CNSeniorious000** [comment]
Thank you for reporting this. In [v0.2.1.1.post4](https://pypi.org/project/partial-json-parser/0.2.1.1.post4/), I updated README to recommend `from partial_json_parser import *` (and support `from partial_json_parser.options import *` too for backward compatibility).
